os:
  - linux
dist: xenial
language: php

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - DOCKER_REPOSITORY=$DOCKER_USERNAME/my-thi.ml

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
   - composer install

script:
  - composer test || travis_terminate 1;
  - docker build -t mythi . || travis_terminate 1;

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

deploy:
  provider: script
  script: ./.travis/dockerhub
  on:
    branch: master
    php: 7.3
